version: '3.8'

services:
  telegram-bot:
    build: .
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    command: python main.py

  redirect-server:
    build: .
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    ports:
      - "${REDIRECT_PORT:-8000}:8000"
    command: uvicorn oauth_handler:app --host 0.0.0.0 --port 8000
